/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-10-28 17:08:27 UTC)
 * on 2014-10-31 at 01:55:01 UTC 
 * Modify at your own risk.
 */

package it.polimi.dima.polisocial.entity.postimageendpoint;

/**
 * Service definition for Postimageendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PostimageendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Postimageendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the postimageendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://polimisocial.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "postimageendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Postimageendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Postimageendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getImageFromPostId".
   *
   * This request holds the parameters needed by the postimageendpoint server.  After setting any
   * optional parameters, call the {@link GetImageFromPostId#execute()} method to invoke the remote
   * operation.
   *
   * @param postId
   * @return the request
   */
  public GetImageFromPostId getImageFromPostId(java.lang.Long postId) throws java.io.IOException {
    GetImageFromPostId result = new GetImageFromPostId(postId);
    initialize(result);
    return result;
  }

  public class GetImageFromPostId extends PostimageendpointRequest<it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage> {

    private static final String REST_PATH = "getImageFromPostId";

    /**
     * Create a request for the method "getImageFromPostId".
     *
     * This request holds the parameters needed by the the postimageendpoint server.  After setting
     * any optional parameters, call the {@link GetImageFromPostId#execute()} method to invoke the
     * remote operation. <p> {@link GetImageFromPostId#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param postId
     * @since 1.13
     */
    protected GetImageFromPostId(java.lang.Long postId) {
      super(Postimageendpoint.this, "GET", REST_PATH, null, it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage.class);
      this.postId = com.google.api.client.util.Preconditions.checkNotNull(postId, "Required parameter postId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetImageFromPostId setAlt(java.lang.String alt) {
      return (GetImageFromPostId) super.setAlt(alt);
    }

    @Override
    public GetImageFromPostId setFields(java.lang.String fields) {
      return (GetImageFromPostId) super.setFields(fields);
    }

    @Override
    public GetImageFromPostId setKey(java.lang.String key) {
      return (GetImageFromPostId) super.setKey(key);
    }

    @Override
    public GetImageFromPostId setOauthToken(java.lang.String oauthToken) {
      return (GetImageFromPostId) super.setOauthToken(oauthToken);
    }

    @Override
    public GetImageFromPostId setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetImageFromPostId) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetImageFromPostId setQuotaUser(java.lang.String quotaUser) {
      return (GetImageFromPostId) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetImageFromPostId setUserIp(java.lang.String userIp) {
      return (GetImageFromPostId) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long postId;

    /**

     */
    public java.lang.Long getPostId() {
      return postId;
    }

    public GetImageFromPostId setPostId(java.lang.Long postId) {
      this.postId = postId;
      return this;
    }

    @Override
    public GetImageFromPostId set(String parameterName, Object value) {
      return (GetImageFromPostId) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPostImage".
   *
   * This request holds the parameters needed by the postimageendpoint server.  After setting any
   * optional parameters, call the {@link GetPostImage#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetPostImage getPostImage(java.lang.Long id) throws java.io.IOException {
    GetPostImage result = new GetPostImage(id);
    initialize(result);
    return result;
  }

  public class GetPostImage extends PostimageendpointRequest<it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage> {

    private static final String REST_PATH = "postimage/{id}";

    /**
     * Create a request for the method "getPostImage".
     *
     * This request holds the parameters needed by the the postimageendpoint server.  After setting
     * any optional parameters, call the {@link GetPostImage#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPostImage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPostImage(java.lang.Long id) {
      super(Postimageendpoint.this, "GET", REST_PATH, null, it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPostImage setAlt(java.lang.String alt) {
      return (GetPostImage) super.setAlt(alt);
    }

    @Override
    public GetPostImage setFields(java.lang.String fields) {
      return (GetPostImage) super.setFields(fields);
    }

    @Override
    public GetPostImage setKey(java.lang.String key) {
      return (GetPostImage) super.setKey(key);
    }

    @Override
    public GetPostImage setOauthToken(java.lang.String oauthToken) {
      return (GetPostImage) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPostImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPostImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPostImage setQuotaUser(java.lang.String quotaUser) {
      return (GetPostImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPostImage setUserIp(java.lang.String userIp) {
      return (GetPostImage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPostImage setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPostImage set(String parameterName, Object value) {
      return (GetPostImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPostImage".
   *
   * This request holds the parameters needed by the postimageendpoint server.  After setting any
   * optional parameters, call the {@link InsertPostImage#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage}
   * @return the request
   */
  public InsertPostImage insertPostImage(it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage content) throws java.io.IOException {
    InsertPostImage result = new InsertPostImage(content);
    initialize(result);
    return result;
  }

  public class InsertPostImage extends PostimageendpointRequest<it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage> {

    private static final String REST_PATH = "postimage";

    /**
     * Create a request for the method "insertPostImage".
     *
     * This request holds the parameters needed by the the postimageendpoint server.  After setting
     * any optional parameters, call the {@link InsertPostImage#execute()} method to invoke the remote
     * operation. <p> {@link InsertPostImage#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage}
     * @since 1.13
     */
    protected InsertPostImage(it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage content) {
      super(Postimageendpoint.this, "POST", REST_PATH, content, it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage.class);
    }

    @Override
    public InsertPostImage setAlt(java.lang.String alt) {
      return (InsertPostImage) super.setAlt(alt);
    }

    @Override
    public InsertPostImage setFields(java.lang.String fields) {
      return (InsertPostImage) super.setFields(fields);
    }

    @Override
    public InsertPostImage setKey(java.lang.String key) {
      return (InsertPostImage) super.setKey(key);
    }

    @Override
    public InsertPostImage setOauthToken(java.lang.String oauthToken) {
      return (InsertPostImage) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPostImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPostImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPostImage setQuotaUser(java.lang.String quotaUser) {
      return (InsertPostImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPostImage setUserIp(java.lang.String userIp) {
      return (InsertPostImage) super.setUserIp(userIp);
    }

    @Override
    public InsertPostImage set(String parameterName, Object value) {
      return (InsertPostImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPostImage".
   *
   * This request holds the parameters needed by the postimageendpoint server.  After setting any
   * optional parameters, call the {@link ListPostImage#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPostImage listPostImage() throws java.io.IOException {
    ListPostImage result = new ListPostImage();
    initialize(result);
    return result;
  }

  public class ListPostImage extends PostimageendpointRequest<it.polimi.dima.polisocial.entity.postimageendpoint.model.CollectionResponsePostImage> {

    private static final String REST_PATH = "postimage";

    /**
     * Create a request for the method "listPostImage".
     *
     * This request holds the parameters needed by the the postimageendpoint server.  After setting
     * any optional parameters, call the {@link ListPostImage#execute()} method to invoke the remote
     * operation. <p> {@link ListPostImage#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPostImage() {
      super(Postimageendpoint.this, "GET", REST_PATH, null, it.polimi.dima.polisocial.entity.postimageendpoint.model.CollectionResponsePostImage.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPostImage setAlt(java.lang.String alt) {
      return (ListPostImage) super.setAlt(alt);
    }

    @Override
    public ListPostImage setFields(java.lang.String fields) {
      return (ListPostImage) super.setFields(fields);
    }

    @Override
    public ListPostImage setKey(java.lang.String key) {
      return (ListPostImage) super.setKey(key);
    }

    @Override
    public ListPostImage setOauthToken(java.lang.String oauthToken) {
      return (ListPostImage) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPostImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPostImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPostImage setQuotaUser(java.lang.String quotaUser) {
      return (ListPostImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPostImage setUserIp(java.lang.String userIp) {
      return (ListPostImage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPostImage setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPostImage setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPostImage set(String parameterName, Object value) {
      return (ListPostImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePostImage".
   *
   * This request holds the parameters needed by the postimageendpoint server.  After setting any
   * optional parameters, call the {@link RemovePostImage#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePostImage removePostImage(java.lang.Long id) throws java.io.IOException {
    RemovePostImage result = new RemovePostImage(id);
    initialize(result);
    return result;
  }

  public class RemovePostImage extends PostimageendpointRequest<Void> {

    private static final String REST_PATH = "postimage/{id}";

    /**
     * Create a request for the method "removePostImage".
     *
     * This request holds the parameters needed by the the postimageendpoint server.  After setting
     * any optional parameters, call the {@link RemovePostImage#execute()} method to invoke the remote
     * operation. <p> {@link RemovePostImage#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePostImage(java.lang.Long id) {
      super(Postimageendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePostImage setAlt(java.lang.String alt) {
      return (RemovePostImage) super.setAlt(alt);
    }

    @Override
    public RemovePostImage setFields(java.lang.String fields) {
      return (RemovePostImage) super.setFields(fields);
    }

    @Override
    public RemovePostImage setKey(java.lang.String key) {
      return (RemovePostImage) super.setKey(key);
    }

    @Override
    public RemovePostImage setOauthToken(java.lang.String oauthToken) {
      return (RemovePostImage) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePostImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePostImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePostImage setQuotaUser(java.lang.String quotaUser) {
      return (RemovePostImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePostImage setUserIp(java.lang.String userIp) {
      return (RemovePostImage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePostImage setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePostImage set(String parameterName, Object value) {
      return (RemovePostImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePostImage".
   *
   * This request holds the parameters needed by the postimageendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePostImage#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage}
   * @return the request
   */
  public UpdatePostImage updatePostImage(it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage content) throws java.io.IOException {
    UpdatePostImage result = new UpdatePostImage(content);
    initialize(result);
    return result;
  }

  public class UpdatePostImage extends PostimageendpointRequest<it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage> {

    private static final String REST_PATH = "postimage";

    /**
     * Create a request for the method "updatePostImage".
     *
     * This request holds the parameters needed by the the postimageendpoint server.  After setting
     * any optional parameters, call the {@link UpdatePostImage#execute()} method to invoke the remote
     * operation. <p> {@link UpdatePostImage#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage}
     * @since 1.13
     */
    protected UpdatePostImage(it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage content) {
      super(Postimageendpoint.this, "PUT", REST_PATH, content, it.polimi.dima.polisocial.entity.postimageendpoint.model.PostImage.class);
    }

    @Override
    public UpdatePostImage setAlt(java.lang.String alt) {
      return (UpdatePostImage) super.setAlt(alt);
    }

    @Override
    public UpdatePostImage setFields(java.lang.String fields) {
      return (UpdatePostImage) super.setFields(fields);
    }

    @Override
    public UpdatePostImage setKey(java.lang.String key) {
      return (UpdatePostImage) super.setKey(key);
    }

    @Override
    public UpdatePostImage setOauthToken(java.lang.String oauthToken) {
      return (UpdatePostImage) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePostImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePostImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePostImage setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePostImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePostImage setUserIp(java.lang.String userIp) {
      return (UpdatePostImage) super.setUserIp(userIp);
    }

    @Override
    public UpdatePostImage set(String parameterName, Object value) {
      return (UpdatePostImage) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Postimageendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Postimageendpoint}. */
    @Override
    public Postimageendpoint build() {
      return new Postimageendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PostimageendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPostimageendpointRequestInitializer(
        PostimageendpointRequestInitializer postimageendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(postimageendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
