/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-09 17:08:39 UTC)
 * on 2014-07-15 at 01:36:04 UTC 
 * Modify at your own risk.
 */

package it.polimi.dima.polisocial.foursquare.foursquareendpoint.model;

/**
 * Model definition for PrintWriter.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the foursquareendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PrintWriter extends com.google.api.client.json.GenericJson {

  @Override
  public PrintWriter set(String fieldName, Object value) {
    return (PrintWriter) super.set(fieldName, value);
  }

  @Override
  public PrintWriter clone() {
    return (PrintWriter) super.clone();
  }

}
