/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-28 at 01:36:39 UTC 
 * Modify at your own risk.
 */

package it.polimi.dima.polisocial.entity.likeendpoint;

/**
 * Service definition for Likeendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link LikeendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Likeendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the likeendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://polimisocial.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "likeendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Likeendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Likeendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getLike".
   *
   * This request holds the parameters needed by the likeendpoint server.  After setting any optional
   * parameters, call the {@link GetLike#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetLike getLike(java.lang.Long id) throws java.io.IOException {
    GetLike result = new GetLike(id);
    initialize(result);
    return result;
  }

  public class GetLike extends LikeendpointRequest<it.polimi.dima.polisocial.entity.likeendpoint.model.Like> {

    private static final String REST_PATH = "like/{id}";

    /**
     * Create a request for the method "getLike".
     *
     * This request holds the parameters needed by the the likeendpoint server.  After setting any
     * optional parameters, call the {@link GetLike#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetLike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetLike(java.lang.Long id) {
      super(Likeendpoint.this, "GET", REST_PATH, null, it.polimi.dima.polisocial.entity.likeendpoint.model.Like.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetLike setAlt(java.lang.String alt) {
      return (GetLike) super.setAlt(alt);
    }

    @Override
    public GetLike setFields(java.lang.String fields) {
      return (GetLike) super.setFields(fields);
    }

    @Override
    public GetLike setKey(java.lang.String key) {
      return (GetLike) super.setKey(key);
    }

    @Override
    public GetLike setOauthToken(java.lang.String oauthToken) {
      return (GetLike) super.setOauthToken(oauthToken);
    }

    @Override
    public GetLike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetLike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetLike setQuotaUser(java.lang.String quotaUser) {
      return (GetLike) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetLike setUserIp(java.lang.String userIp) {
      return (GetLike) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetLike setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetLike set(String parameterName, Object value) {
      return (GetLike) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPostLike".
   *
   * This request holds the parameters needed by the likeendpoint server.  After setting any optional
   * parameters, call the {@link GetPostLike#execute()} method to invoke the remote operation.
   *
   * @param postId
   * @return the request
   */
  public GetPostLike getPostLike(java.lang.Long postId) throws java.io.IOException {
    GetPostLike result = new GetPostLike(postId);
    initialize(result);
    return result;
  }

  public class GetPostLike extends LikeendpointRequest<it.polimi.dima.polisocial.entity.likeendpoint.model.ResponseObject> {

    private static final String REST_PATH = "responseobject/{postId}";

    /**
     * Create a request for the method "getPostLike".
     *
     * This request holds the parameters needed by the the likeendpoint server.  After setting any
     * optional parameters, call the {@link GetPostLike#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPostLike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param postId
     * @since 1.13
     */
    protected GetPostLike(java.lang.Long postId) {
      super(Likeendpoint.this, "GET", REST_PATH, null, it.polimi.dima.polisocial.entity.likeendpoint.model.ResponseObject.class);
      this.postId = com.google.api.client.util.Preconditions.checkNotNull(postId, "Required parameter postId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPostLike setAlt(java.lang.String alt) {
      return (GetPostLike) super.setAlt(alt);
    }

    @Override
    public GetPostLike setFields(java.lang.String fields) {
      return (GetPostLike) super.setFields(fields);
    }

    @Override
    public GetPostLike setKey(java.lang.String key) {
      return (GetPostLike) super.setKey(key);
    }

    @Override
    public GetPostLike setOauthToken(java.lang.String oauthToken) {
      return (GetPostLike) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPostLike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPostLike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPostLike setQuotaUser(java.lang.String quotaUser) {
      return (GetPostLike) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPostLike setUserIp(java.lang.String userIp) {
      return (GetPostLike) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long postId;

    /**

     */
    public java.lang.Long getPostId() {
      return postId;
    }

    public GetPostLike setPostId(java.lang.Long postId) {
      this.postId = postId;
      return this;
    }

    @Override
    public GetPostLike set(String parameterName, Object value) {
      return (GetPostLike) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertLike".
   *
   * This request holds the parameters needed by the likeendpoint server.  After setting any optional
   * parameters, call the {@link InsertLike#execute()} method to invoke the remote operation.
   *
   * @param content the {@link it.polimi.dima.polisocial.entity.likeendpoint.model.Like}
   * @return the request
   */
  public InsertLike insertLike(it.polimi.dima.polisocial.entity.likeendpoint.model.Like content) throws java.io.IOException {
    InsertLike result = new InsertLike(content);
    initialize(result);
    return result;
  }

  public class InsertLike extends LikeendpointRequest<it.polimi.dima.polisocial.entity.likeendpoint.model.Like> {

    private static final String REST_PATH = "like";

    /**
     * Create a request for the method "insertLike".
     *
     * This request holds the parameters needed by the the likeendpoint server.  After setting any
     * optional parameters, call the {@link InsertLike#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertLike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link it.polimi.dima.polisocial.entity.likeendpoint.model.Like}
     * @since 1.13
     */
    protected InsertLike(it.polimi.dima.polisocial.entity.likeendpoint.model.Like content) {
      super(Likeendpoint.this, "POST", REST_PATH, content, it.polimi.dima.polisocial.entity.likeendpoint.model.Like.class);
    }

    @Override
    public InsertLike setAlt(java.lang.String alt) {
      return (InsertLike) super.setAlt(alt);
    }

    @Override
    public InsertLike setFields(java.lang.String fields) {
      return (InsertLike) super.setFields(fields);
    }

    @Override
    public InsertLike setKey(java.lang.String key) {
      return (InsertLike) super.setKey(key);
    }

    @Override
    public InsertLike setOauthToken(java.lang.String oauthToken) {
      return (InsertLike) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertLike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertLike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertLike setQuotaUser(java.lang.String quotaUser) {
      return (InsertLike) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertLike setUserIp(java.lang.String userIp) {
      return (InsertLike) super.setUserIp(userIp);
    }

    @Override
    public InsertLike set(String parameterName, Object value) {
      return (InsertLike) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listLike".
   *
   * This request holds the parameters needed by the likeendpoint server.  After setting any optional
   * parameters, call the {@link ListLike#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListLike listLike() throws java.io.IOException {
    ListLike result = new ListLike();
    initialize(result);
    return result;
  }

  public class ListLike extends LikeendpointRequest<it.polimi.dima.polisocial.entity.likeendpoint.model.CollectionResponseLike> {

    private static final String REST_PATH = "like";

    /**
     * Create a request for the method "listLike".
     *
     * This request holds the parameters needed by the the likeendpoint server.  After setting any
     * optional parameters, call the {@link ListLike#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListLike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListLike() {
      super(Likeendpoint.this, "GET", REST_PATH, null, it.polimi.dima.polisocial.entity.likeendpoint.model.CollectionResponseLike.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListLike setAlt(java.lang.String alt) {
      return (ListLike) super.setAlt(alt);
    }

    @Override
    public ListLike setFields(java.lang.String fields) {
      return (ListLike) super.setFields(fields);
    }

    @Override
    public ListLike setKey(java.lang.String key) {
      return (ListLike) super.setKey(key);
    }

    @Override
    public ListLike setOauthToken(java.lang.String oauthToken) {
      return (ListLike) super.setOauthToken(oauthToken);
    }

    @Override
    public ListLike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListLike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListLike setQuotaUser(java.lang.String quotaUser) {
      return (ListLike) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListLike setUserIp(java.lang.String userIp) {
      return (ListLike) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListLike setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListLike setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListLike set(String parameterName, Object value) {
      return (ListLike) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeLike".
   *
   * This request holds the parameters needed by the likeendpoint server.  After setting any optional
   * parameters, call the {@link RemoveLike#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveLike removeLike(java.lang.Long id) throws java.io.IOException {
    RemoveLike result = new RemoveLike(id);
    initialize(result);
    return result;
  }

  public class RemoveLike extends LikeendpointRequest<Void> {

    private static final String REST_PATH = "like/{id}";

    /**
     * Create a request for the method "removeLike".
     *
     * This request holds the parameters needed by the the likeendpoint server.  After setting any
     * optional parameters, call the {@link RemoveLike#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveLike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveLike(java.lang.Long id) {
      super(Likeendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveLike setAlt(java.lang.String alt) {
      return (RemoveLike) super.setAlt(alt);
    }

    @Override
    public RemoveLike setFields(java.lang.String fields) {
      return (RemoveLike) super.setFields(fields);
    }

    @Override
    public RemoveLike setKey(java.lang.String key) {
      return (RemoveLike) super.setKey(key);
    }

    @Override
    public RemoveLike setOauthToken(java.lang.String oauthToken) {
      return (RemoveLike) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveLike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveLike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveLike setQuotaUser(java.lang.String quotaUser) {
      return (RemoveLike) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveLike setUserIp(java.lang.String userIp) {
      return (RemoveLike) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveLike setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveLike set(String parameterName, Object value) {
      return (RemoveLike) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateLike".
   *
   * This request holds the parameters needed by the likeendpoint server.  After setting any optional
   * parameters, call the {@link UpdateLike#execute()} method to invoke the remote operation.
   *
   * @param content the {@link it.polimi.dima.polisocial.entity.likeendpoint.model.Like}
   * @return the request
   */
  public UpdateLike updateLike(it.polimi.dima.polisocial.entity.likeendpoint.model.Like content) throws java.io.IOException {
    UpdateLike result = new UpdateLike(content);
    initialize(result);
    return result;
  }

  public class UpdateLike extends LikeendpointRequest<it.polimi.dima.polisocial.entity.likeendpoint.model.Like> {

    private static final String REST_PATH = "like";

    /**
     * Create a request for the method "updateLike".
     *
     * This request holds the parameters needed by the the likeendpoint server.  After setting any
     * optional parameters, call the {@link UpdateLike#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateLike#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link it.polimi.dima.polisocial.entity.likeendpoint.model.Like}
     * @since 1.13
     */
    protected UpdateLike(it.polimi.dima.polisocial.entity.likeendpoint.model.Like content) {
      super(Likeendpoint.this, "PUT", REST_PATH, content, it.polimi.dima.polisocial.entity.likeendpoint.model.Like.class);
    }

    @Override
    public UpdateLike setAlt(java.lang.String alt) {
      return (UpdateLike) super.setAlt(alt);
    }

    @Override
    public UpdateLike setFields(java.lang.String fields) {
      return (UpdateLike) super.setFields(fields);
    }

    @Override
    public UpdateLike setKey(java.lang.String key) {
      return (UpdateLike) super.setKey(key);
    }

    @Override
    public UpdateLike setOauthToken(java.lang.String oauthToken) {
      return (UpdateLike) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateLike setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateLike) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateLike setQuotaUser(java.lang.String quotaUser) {
      return (UpdateLike) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateLike setUserIp(java.lang.String userIp) {
      return (UpdateLike) super.setUserIp(userIp);
    }

    @Override
    public UpdateLike set(String parameterName, Object value) {
      return (UpdateLike) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Likeendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Likeendpoint}. */
    @Override
    public Likeendpoint build() {
      return new Likeendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link LikeendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setLikeendpointRequestInitializer(
        LikeendpointRequestInitializer likeendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(likeendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
