/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-09 17:08:39 UTC)
 * on 2014-07-23 at 15:42:53 UTC 
 * Modify at your own risk.
 */

package it.polimi.dima.polisocial.foursquare.foursquareendpoint;

/**
 * Service definition for Foursquareendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link FoursquareendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Foursquareendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the foursquareendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "foursquareendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Foursquareendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Foursquareendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the FoursquarePolisocialAPI collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Foursquareendpoint foursquareendpoint = new Foursquareendpoint(...);}
   *   {@code Foursquareendpoint.FoursquarePolisocialAPI.List request = foursquareendpoint.foursquarePolisocialAPI().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public FoursquarePolisocialAPI foursquarePolisocialAPI() {
    return new FoursquarePolisocialAPI();
  }

  /**
   * The "foursquarePolisocialAPI" collection of methods.
   */
  public class FoursquarePolisocialAPI {

    /**
     * Create a request for the method "foursquarePolisocialAPI.authenticationRequest".
     *
     * This request holds the parameters needed by the foursquareendpoint server.  After setting any
     * optional parameters, call the {@link AuthenticationRequest#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link it.polimi.dima.polisocial.foursquare.foursquareendpoint.model.HttpServletResponse}
     * @return the request
     */
    public AuthenticationRequest authenticationRequest(it.polimi.dima.polisocial.foursquare.foursquareendpoint.model.HttpServletResponse content) throws java.io.IOException {
      AuthenticationRequest result = new AuthenticationRequest(content);
      initialize(result);
      return result;
    }

    public class AuthenticationRequest extends FoursquareendpointRequest<Void> {

      private static final String REST_PATH = "authenticationRequest";

      /**
       * Create a request for the method "foursquarePolisocialAPI.authenticationRequest".
       *
       * This request holds the parameters needed by the the foursquareendpoint server.  After setting
       * any optional parameters, call the {@link AuthenticationRequest#execute()} method to invoke the
       * remote operation. <p> {@link AuthenticationRequest#initialize(com.google.api.client.googleapis.
       * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
       * after invoking the constructor. </p>
       *
       * @param content the {@link it.polimi.dima.polisocial.foursquare.foursquareendpoint.model.HttpServletResponse}
       * @since 1.13
       */
      protected AuthenticationRequest(it.polimi.dima.polisocial.foursquare.foursquareendpoint.model.HttpServletResponse content) {
        super(Foursquareendpoint.this, "POST", REST_PATH, content, Void.class);
      }

      @Override
      public AuthenticationRequest setAlt(java.lang.String alt) {
        return (AuthenticationRequest) super.setAlt(alt);
      }

      @Override
      public AuthenticationRequest setFields(java.lang.String fields) {
        return (AuthenticationRequest) super.setFields(fields);
      }

      @Override
      public AuthenticationRequest setKey(java.lang.String key) {
        return (AuthenticationRequest) super.setKey(key);
      }

      @Override
      public AuthenticationRequest setOauthToken(java.lang.String oauthToken) {
        return (AuthenticationRequest) super.setOauthToken(oauthToken);
      }

      @Override
      public AuthenticationRequest setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (AuthenticationRequest) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public AuthenticationRequest setQuotaUser(java.lang.String quotaUser) {
        return (AuthenticationRequest) super.setQuotaUser(quotaUser);
      }

      @Override
      public AuthenticationRequest setUserIp(java.lang.String userIp) {
        return (AuthenticationRequest) super.setUserIp(userIp);
      }

      @Override
      public AuthenticationRequest set(String parameterName, Object value) {
        return (AuthenticationRequest) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "foursquarePolisocialAPI.handleCallback".
     *
     * This request holds the parameters needed by the foursquareendpoint server.  After setting any
     * optional parameters, call the {@link HandleCallback#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link it.polimi.dima.polisocial.foursquare.foursquareendpoint.model.HttpServletResponse}
     * @return the request
     */
    public HandleCallback handleCallback(it.polimi.dima.polisocial.foursquare.foursquareendpoint.model.HttpServletResponse content) throws java.io.IOException {
      HandleCallback result = new HandleCallback(content);
      initialize(result);
      return result;
    }

    public class HandleCallback extends FoursquareendpointRequest<Void> {

      private static final String REST_PATH = "handleCallback";

      /**
       * Create a request for the method "foursquarePolisocialAPI.handleCallback".
       *
       * This request holds the parameters needed by the the foursquareendpoint server.  After setting
       * any optional parameters, call the {@link HandleCallback#execute()} method to invoke the remote
       * operation. <p> {@link HandleCallback#initialize(com.google.api.client.googleapis.services.Abstr
       * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param content the {@link it.polimi.dima.polisocial.foursquare.foursquareendpoint.model.HttpServletResponse}
       * @since 1.13
       */
      protected HandleCallback(it.polimi.dima.polisocial.foursquare.foursquareendpoint.model.HttpServletResponse content) {
        super(Foursquareendpoint.this, "POST", REST_PATH, content, Void.class);
      }

      @Override
      public HandleCallback setAlt(java.lang.String alt) {
        return (HandleCallback) super.setAlt(alt);
      }

      @Override
      public HandleCallback setFields(java.lang.String fields) {
        return (HandleCallback) super.setFields(fields);
      }

      @Override
      public HandleCallback setKey(java.lang.String key) {
        return (HandleCallback) super.setKey(key);
      }

      @Override
      public HandleCallback setOauthToken(java.lang.String oauthToken) {
        return (HandleCallback) super.setOauthToken(oauthToken);
      }

      @Override
      public HandleCallback setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (HandleCallback) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public HandleCallback setQuotaUser(java.lang.String quotaUser) {
        return (HandleCallback) super.setQuotaUser(quotaUser);
      }

      @Override
      public HandleCallback setUserIp(java.lang.String userIp) {
        return (HandleCallback) super.setUserIp(userIp);
      }

      @Override
      public HandleCallback set(String parameterName, Object value) {
        return (HandleCallback) super.set(parameterName, value);
      }
    }

  }

  /**
   * Create a request for the method "searchVenues".
   *
   * This request holds the parameters needed by the foursquareendpoint server.  After setting any
   * optional parameters, call the {@link SearchVenues#execute()} method to invoke the remote
   * operation.
   *
   * @param ll
   * @return the request
   */
  public SearchVenues searchVenues(java.lang.String ll) throws java.io.IOException {
    SearchVenues result = new SearchVenues(ll);
    initialize(result);
    return result;
  }

  public class SearchVenues extends FoursquareendpointRequest<it.polimi.dima.polisocial.foursquare.foursquareendpoint.model.StringCollection> {

    private static final String REST_PATH = "searchVenues/{ll}";

    /**
     * Create a request for the method "searchVenues".
     *
     * This request holds the parameters needed by the the foursquareendpoint server.  After setting
     * any optional parameters, call the {@link SearchVenues#execute()} method to invoke the remote
     * operation. <p> {@link
     * SearchVenues#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param ll
     * @since 1.13
     */
    protected SearchVenues(java.lang.String ll) {
      super(Foursquareendpoint.this, "POST", REST_PATH, null, it.polimi.dima.polisocial.foursquare.foursquareendpoint.model.StringCollection.class);
      this.ll = com.google.api.client.util.Preconditions.checkNotNull(ll, "Required parameter ll must be specified.");
    }

    @Override
    public SearchVenues setAlt(java.lang.String alt) {
      return (SearchVenues) super.setAlt(alt);
    }

    @Override
    public SearchVenues setFields(java.lang.String fields) {
      return (SearchVenues) super.setFields(fields);
    }

    @Override
    public SearchVenues setKey(java.lang.String key) {
      return (SearchVenues) super.setKey(key);
    }

    @Override
    public SearchVenues setOauthToken(java.lang.String oauthToken) {
      return (SearchVenues) super.setOauthToken(oauthToken);
    }

    @Override
    public SearchVenues setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SearchVenues) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SearchVenues setQuotaUser(java.lang.String quotaUser) {
      return (SearchVenues) super.setQuotaUser(quotaUser);
    }

    @Override
    public SearchVenues setUserIp(java.lang.String userIp) {
      return (SearchVenues) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String ll;

    /**

     */
    public java.lang.String getLl() {
      return ll;
    }

    public SearchVenues setLl(java.lang.String ll) {
      this.ll = ll;
      return this;
    }

    @Override
    public SearchVenues set(String parameterName, Object value) {
      return (SearchVenues) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Foursquareendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Foursquareendpoint}. */
    @Override
    public Foursquareendpoint build() {
      return new Foursquareendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link FoursquareendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setFoursquareendpointRequestInitializer(
        FoursquareendpointRequestInitializer foursquareendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(foursquareendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
